version: '3.8'
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    expose:
      - "3000"
    restart: always
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - dev

  db:
    image: postgres:16-alpine
    env_file:
      - ./backend/.env
    expose:
      - "5432"
    ports:
      - "5439:5432"
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    image: frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - dev

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/app/frontend
    depends_on:
      - backend
      - frontend
    networks:
      - dev

networks:
  dev:
